name: Tweet Snapshot Part 2

on:
  schedule:
    - cron: '20 22 * * *'  # 22:15 UTC
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requests
        run: pip install requests

      - name: Fetch Tweets Part 2
        run: python scripts/multi_fetch_part2.py
        env:
          TWITTER_BEARER_1: ${{ secrets.TWITTER_BEARER_1 }}
          TWITTER_BEARER_2: ${{ secrets.TWITTER_BEARER_2 }}
          TWITTER_BEARER_3: ${{ secrets.TWITTER_BEARER_3 }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Puppeteer
        run: npm install puppeteer@21.3.8

      - name: Install Chrome
        run: npx puppeteer browsers install chrome


      - name: Screenshot Tweets
        run: node scripts/screenshot_tweets.js

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add screenshots/
          git add public/community_feed/
          git commit -m "🖼️ Part 2 tweet snapshots"
          git push
        continue-on-error: true
